import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useEffect, useState } from "react";
import { ParamedicalDashboardSidebar } from "@/components/ParamedicalDashboardSidebar";
import { Search, FileText, MessageCircle, Calendar, ChevronRight, UserCircle2, Plus, } from "lucide-react";
const tok = () => localStorage.getItem("megacare_token") ?? "";
const statusColors = {
    Actif: "bg-green-100 text-green-700",
    Suivi: "bg-blue-100 text-blue-700",
    Clôturé: "bg-slate-100 text-slate-500",
};
const statusFilters = ["Tous", "Actif", "Suivi", "Clôturé"];
export default function ParamedicalPatientsPage() {
    const [patients, setPatients] = useState([]);
    const [search, setSearch] = useState("");
    const [filterStatus, setFilterStatus] = useState("Tous");
    const [selected, setSelected] = useState(null);
    useEffect(() => {
        fetch("/api/paramedical/patients", { headers: { Authorization: `Bearer ${tok()}` } })
            .then((r) => r.json())
            .then((d) => setPatients(Array.isArray(d) ? d : []))
            .catch(() => { });
    }, []);
    const filtered = patients.filter((p) => {
        const matchSearch = p.name.toLowerCase().includes(search.toLowerCase()) ||
            p.condition.toLowerCase().includes(search.toLowerCase()) ||
            p.careType.toLowerCase().includes(search.toLowerCase());
        const matchStatus = filterStatus === "Tous" || p.status === filterStatus;
        return matchSearch && matchStatus;
    });
    return (_jsxs("div", { className: "flex min-h-screen bg-background", children: [_jsx(ParamedicalDashboardSidebar, {}), _jsxs("div", { className: "flex-1 flex flex-col min-w-0", children: [_jsx("div", { className: "px-6 py-5 border-b border-border bg-card/50 shrink-0", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-xl font-bold text-foreground", children: "Patients" }), _jsxs("p", { className: "text-sm text-muted-foreground mt-0.5", children: [patients.length, " patients \u2014 ", patients.filter((p) => p.status === "Actif").length, " actifs"] })] }), _jsxs("button", { className: "flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 transition", children: [_jsx(Plus, { size: 15 }), "Nouveau patient"] })] }) }), _jsxs("main", { className: "flex-1 overflow-y-auto p-6 space-y-5", children: [_jsxs("div", { className: "flex flex-col sm:flex-row gap-3", children: [_jsxs("div", { className: "relative flex-1", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground", size: 16 }), _jsx("input", { type: "text", placeholder: "Rechercher par nom, pathologie, type de soin...", value: search, onChange: (e) => setSearch(e.target.value), className: "w-full pl-9 pr-4 py-2.5 bg-card border border-border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-primary/40" })] }), _jsx("div", { className: "flex gap-2 flex-wrap", children: statusFilters.map((s) => (_jsx("button", { onClick: () => setFilterStatus(s), className: `px-3 py-2 rounded-lg text-xs font-medium border transition ${filterStatus === s
                                                ? "border-primary bg-primary/5 text-primary"
                                                : "border-border bg-card text-muted-foreground hover:border-primary/40"}`, children: s }, s))) })] }), filtered.length === 0 ? (_jsx("div", { className: "bg-card rounded-xl border border-border p-10 text-center text-muted-foreground text-sm", children: "Aucun patient trouv\u00E9." })) : (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4", children: filtered.map((patient) => (_jsxs("div", { className: "bg-card rounded-xl border border-border p-5 space-y-4 hover:shadow-md hover:border-primary/30 transition-all", children: [_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-gradient-to-br from-primary/30 to-primary/10 flex items-center justify-center shrink-0", children: _jsx(UserCircle2, { size: 22, className: "text-primary" }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsx("p", { className: "font-semibold text-sm text-foreground truncate", children: patient.name }), _jsx("span", { className: `text-xs px-2 py-0.5 rounded-full font-medium ${statusColors[patient.status]}`, children: patient.status })] }), _jsxs("p", { className: "text-xs text-muted-foreground", children: [patient.age, " ans \u00B7 ", patient.careType] })] })] }), _jsxs("div", { className: "bg-muted/40 rounded-lg px-3 py-2", children: [_jsx("p", { className: "text-xs text-muted-foreground mb-0.5", children: "Pathologie" }), _jsx("p", { className: "text-sm text-foreground", children: patient.condition })] }), _jsxs("div", { className: "flex items-center gap-1.5 text-xs text-muted-foreground", children: [_jsx(Calendar, { size: 12 }), patient.nextAppointment
                                                    ? _jsxs(_Fragment, { children: ["Prochain RDV : ", _jsx("span", { className: "font-medium text-foreground", children: new Date(patient.nextAppointment).toLocaleDateString("fr-FR", { day: "numeric", month: "long" }) })] })
                                                    : "Aucun rendez-vous planifié"] }), _jsxs("div", { className: "flex gap-2 pt-1", children: [_jsxs("button", { className: "flex-1 flex items-center justify-center gap-1.5 px-3 py-2 text-xs border border-border rounded-lg hover:border-primary hover:text-primary transition", children: [_jsx(FileText, { size: 13 }), "Dossier m\u00E9dical"] }), _jsxs("button", { className: "flex-1 flex items-center justify-center gap-1.5 px-3 py-2 text-xs border border-border rounded-lg hover:border-primary hover:text-primary transition", children: [_jsx(MessageCircle, { size: 13 }), "Message"] }), _jsx("button", { onClick: () => setSelected(patient), className: "p-2 border border-border rounded-lg hover:border-primary hover:text-primary transition", children: _jsx(ChevronRight, { size: 14 }) })] })] }, patient.id))) }))] })] }), selected && (_jsxs("div", { className: "fixed inset-0 z-50 flex justify-end", children: [_jsx("div", { className: "absolute inset-0 bg-black/40", onClick: () => setSelected(null) }), _jsxs("aside", { className: "relative w-full max-w-sm bg-card border-l border-border flex flex-col shadow-2xl", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-5 border-b border-border", children: [_jsx("h2", { className: "font-semibold text-foreground", children: "Fiche patient" }), _jsx("button", { onClick: () => setSelected(null), className: "text-muted-foreground hover:text-foreground transition text-xl leading-none", children: "\u00D7" })] }), _jsxs("div", { className: "flex-1 overflow-y-auto p-6 space-y-5", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-14 h-14 rounded-full bg-gradient-to-br from-primary/30 to-primary/10 flex items-center justify-center", children: _jsx(UserCircle2, { size: 32, className: "text-primary" }) }), _jsxs("div", { children: [_jsx("p", { className: "font-bold text-foreground", children: selected.name }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [selected.age, " ans"] }), _jsx("span", { className: `text-xs px-2 py-0.5 rounded-full font-medium ${statusColors[selected.status]}`, children: selected.status })] })] }), _jsx("div", { className: "space-y-3", children: [
                                            { label: "Pathologie", value: selected.condition },
                                            { label: "Type de soin", value: selected.careType },
                                            { label: "Téléphone", value: selected.phone },
                                            {
                                                label: "Prochain RDV",
                                                value: selected.nextAppointment
                                                    ? new Date(selected.nextAppointment).toLocaleDateString("fr-FR", { weekday: "long", day: "numeric", month: "long" })
                                                    : "Non planifié",
                                            },
                                        ].map((row) => (_jsxs("div", { className: "bg-muted/40 rounded-lg px-4 py-3", children: [_jsx("p", { className: "text-xs text-muted-foreground mb-0.5", children: row.label }), _jsx("p", { className: "text-sm font-medium text-foreground", children: row.value })] }, row.label))) }), _jsxs("div", { className: "space-y-2 pt-1", children: [_jsxs("button", { className: "w-full flex items-center gap-2 px-4 py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-medium hover:bg-primary/90 transition", children: [_jsx(FileText, { size: 15 }), "Ouvrir le dossier m\u00E9dical"] }), _jsxs("button", { className: "w-full flex items-center gap-2 px-4 py-2.5 border border-border rounded-lg text-sm hover:border-primary hover:text-primary transition", children: [_jsx(MessageCircle, { size: 15 }), "Envoyer un message"] })] })] })] })] }))] }));
}
