// Shared filter constants used across LabosRadiologiePage and ServicesMediauxPage
export const tunisianGovernorates = [
    "Tunis",
    "Ariana",
    "Ben Arous",
    "Manouba",
    "Nabeul",
    "Zaghouan",
    "Bizerte",
    "Béja",
    "Jendouba",
    "Le Kef",
    "Siliana",
    "Monastir",
    "Mahdia",
    "Sfax",
    "Kairouan",
    "Kasserine",
    "Sidi Bouzid",
    "Sousse",
    "Gabès",
    "Médenine",
    "Tataouine",
    "Gafsa",
    "Tozeur",
    "Kébili",
];
export const examTypeOptions = [
    "Biologie",
    "Hématologie",
    "Microbiologie",
    "Sérologie",
    "Endocrinologie",
    "Imagerie",
    "IRM",
    "Scanner",
    "Échographie",
    "Radiographie",
    "Médecine nucléaire",
];
export const labTypes = ["Laboratoire", "Radiologie", "Mixte"];
export const allServices = [
    "Cardiologie",
    "Chirurgie",
    "Urgences",
    "Maternité",
    "Pédiatrie",
    "Radiologie",
    "Imagerie",
    "Gynécologie",
    "Orthopédie",
    "Neurologie",
    "Dermatologie",
    "Ophtalmologie",
    "ORL",
    "Soins infirmiers",
    "HAD",
];
export const establishmentTypes = [
    "Clinique",
    "Hôpital",
    "HAD",
    "Centre médical",
];
